#! /bin/sh

iptables -t nat -D OUTPUT -p tcp -s 0/0 -d 0/0 -m owner --uid-owner foo2 -j REDIRECT --to-ports 1984
ip6tables -t nat -D OUTPUT -p tcp -s 0/0 -d 0/0 -m owner --uid-owner foo2 -j REDIRECT --to-ports 1984
iptables -t nat -D OUTPUT -p udp -s 0/0 -d 0/0 -m owner --uid-owner foo2 -j REDIRECT --to-ports 9053
ip6tables -t nat -D OUTPUT -p udp -s 0/0 -d 0/0 -m owner --uid-owner foo2 -j REDIRECT --to-ports 9053
