#! /bin/sh

echo "Making archive..."

rm -f /builds/fishy-netbsd-10/f-build.txz 2>/dev/null
cd /
tar vcJpf /builds/fishy-netbsd-10/f-build.txz builds/obj/fishy/obj/sys/arch/amd64/compile/FISHY/ builds/obj/fishy/release/amd64/binary/sets

exit $?
