#! /bin/sh

echo 'Now building... dankmaymay custom kernel:'

cd src && \
	nice -n 20 ./build.sh -T /builds/scratch/dank/tools/ -O /builds/scratch/dank/obj/ -R /builds/scratch/dank/release/ -U -j 8 -m i386 -x kernel=/builds/dankmaymay-netbsd-10/DANKMAYMAY && \
	echo DANKMAYMAY KERNEL BUILD DONE && \
	exit 0

echo FAILURE
exit 1
