#! /bin/sh

echo 'Now building... dankmaymay-current (project) LIVE IMAGE:'

cd src && \
	nice -n 20 ./build.sh -T /off/dank/tools/ -O /off/dank/obj/ -R /off/dank/release/ -U -u -j 8 -m i386 -x live-image && \
	echo DANKMAYMAY LIVE IMAGE BUILD DONE && \
	exit 0

echo FAILURE
exit 1
